version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: wise_reader_db
    environment:
      POSTGRES_USER: wise_user
      POSTGRES_PASSWORD: pwd 
      POSTGRES_DB: wise_db_dev
    ports:
      - "5432:5432"

  wise_reader:
    image: wise_reader
    environment:
      SECRET_KEY_BASE: 25IzIXO+2SSaMEUE/I5KghJ2uWOh8I+C3b4oXmCafbdYDO/xjMHGn5zheNbkoCoq
      DB_NAME: wise_db_dev
      DB_USER: wise_user
      DB_PASS: pwd
      DB_HOST: postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres
