version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: wise_reader_db
    environment:
      POSTGRES_USER: wise_user
      POSTGRES_PASSWORD: pwd 
      POSTGRES_DB: wise_db_dev
    ports:
      - "6543:5432"

